### ISSUE TITLE
[FR] Make the Merchant Reference a setting

### ISSUE THREAD

**Issue by dwhoban** [newism/commerce-afterpay#6]
Currently the plugin uses the Transaction Hash as the Merchant Reference for Afterpay.

Afterpay now require it to match what is being used for the customer order in Craft. The default reference for Craft seems to be `order->shortNumber` but anything could be used in the template.

This could be a setting in the Gateway Config

**Comment by engram-design** [comment]
In the same boat, Afterpay are rejecting our integration, due to `After placing a successful order, the order confirmation number sent to the customer is different to the merchant reference number sent to Afterpay`.

Agreed that this needs to be configurable. I would suggest people use the order numbers or order ID.

It'd be great if we could use the order reference, but that can't be used, because its generated after the order is complete (and already sent to AfterPay). I've raised this in Commerce before with other gateways https://github.com/craftcms/commerce/issues/1074

**Comment by leevigraham** [comment]
See: #18
